swagger: "2.0"

info:
  title: "{{title}}"
  version: "1.0"

consumes:
  - application/json
produces:
  - application/json

basePath: /v1

paths:
  /greeting/{name}:
    get:
      tags: [Demo]
      summary: Generate greeting
      description: Generates a greeting message.
      x-swagger-router-controller: app.app
      operationId: post_greeting
      produces:
        - text/plain
      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          type: string
      responses:
        200:
          description: greeting response
          schema:
            type: string
          examples:
            "text/plain": "Hello John"
