apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: alphacar-backend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alphacar-backend
        tier: backend
        track: stable
    spec:
      containers:
        - name: alphacar-backend
          image: "alphacar/backend"
          ports:
            - name: http
              containerPort: 80
