apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-hdtlw
    field.cattle.io/publicEndpoints: '[{"addresses":["172.20.37.219"],"port":30000,"protocol":"TCP","serviceName":"alphacar-services:backend-nodeport","allNodes":true}]'
  creationTimestamp: null
  generation: 1
  labels:
    workload.user.cattle.io/workloadselector: deployment-alphacar-services-backend
  name: backend
  selfLink: /apis/apps/v1beta2/namespaces/alphacar-services/deployments/backend
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-alphacar-services-backend
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":3000,"dnsName":"backend-nodeport","kind":"NodePort","name":"3000tcp300001","protocol":"TCP","sourcePort":30000}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-alphacar-services-backend
    spec:
      affinity: {}
      containers:
      - args:
        - bash
        - -c
        - sleep 10; cd /root/backend; npm run prd; tail -f /dev/null;
        image: alphacar/backend
        imagePullPolicy: IfNotPresent
        name: backend
        ports:
        - containerPort: 3000
          name: 3000tcp300001
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
