kind: Service
apiVersion: v1
metadata:
  name: frontend
spec:
  selector:
    app: alphacar-browser
    tier: frontend
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: alphacar-browser
        tier: frontend
        track: stable
    spec:
      containers:
        - name: nginx
          image: "alphacar/frontend"
          lifecycle:
            preStop:
              exec:
                command: ["/usr/sbin/nginx", "-s", "quit"]
                