apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-hdtlw
    field.cattle.io/publicEndpoints: '[{"addresses":["172.20.37.219"],"port":31080,"protocol":"TCP","serviceName":"default:jenkins-nodeport","allNodes":true},{"addresses":["172.20.37.219"],"port":31500,"protocol":"TCP","serviceName":"default:jenkins-nodeport","allNodes":true}]'
  creationTimestamp: 2018-09-12T09:16:05Z
  generation: 2
  labels:
    workload.user.cattle.io/workloadselector: deployment-default-jenkins
  name: jenkins
  namespace: default
  resourceVersion: "840808"
  selfLink: /apis/apps/v1beta2/namespaces/default/deployments/jenkins
  uid: 7a1f3201-b66c-11e8-bf5c-00163e0007fd
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-default-jenkins
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":8080,"dnsName":"jenkins-nodeport","kind":"NodePort","name":"8080tcp310801","protocol":"TCP","sourcePort":31080},{"containerPort":50000,"dnsName":"jenkins-nodeport","kind":"NodePort","name":"50000tcp315001","protocol":"TCP","sourcePort":31500}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-default-jenkins
    spec:
      affinity: {}
      containers:
      - image: jenkins/jenkins
        imagePullPolicy: IfNotPresent
        name: jenkins
        ports:
        - containerPort: 8080
          name: 8080tcp310801
          protocol: TCP
        - containerPort: 50000
          name: 50000tcp315001
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: 2018-09-12T09:16:09Z
    lastUpdateTime: 2018-09-12T09:16:09Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: 2018-09-12T09:16:05Z
    lastUpdateTime: 2018-09-12T09:16:09Z
    message: ReplicaSet "jenkins-6ddc976999" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
