apiVersion: apps/v1beta2
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/creatorId: user-hdtlw
  creationTimestamp: null
  generation: 1
  labels:
    workload.user.cattle.io/workloadselector: deployment-alphacar-thirdparty-services-mongodb
  name: mongodb
  selfLink: /apis/apps/v1beta2/namespaces/alphacar-thirdparty-services/deployments/mongodb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: deployment-alphacar-thirdparty-services-mongodb
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        field.cattle.io/ports: '[[{"containerPort":27017,"dnsName":"mongodb-nodeport","kind":"NodePort","name":"27017tcp270171","protocol":"TCP","sourcePort":27017}]]'
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: deployment-alphacar-thirdparty-services-mongodb
    spec:
      affinity: {}
      containers:
      - image: alphacar/mongodb
        imagePullPolicy: IfNotPresent
        name: mongodb
        ports:
        - containerPort: 27017
          name: 27017tcp270171
          protocol: TCP
        resources: {}
        securityContext:
          allowPrivilegeEscalation: false
          privileged: false
          readOnlyRootFilesystem: false
          runAsNonRoot: false
        stdin: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
        volumeMounts:
        - mountPath: /data/db
          name: vol1
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - hostPath:
          path: /data/mongodb
          type: ""
        name: vol1
status: {}
