version: '3'

services:

  ipfs_node:
    build:
      context: ./ipfs_node
      dockerfile: Dockerfile
    image: alphacar/ipfs_node
    container_name: ipfs_node
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ./../../var/ipfs:/root/.ipfs:rw
    command: /root/start.sh

  mongo_db:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: alphacar/mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./../../var/mongodb:/data/db:rw
      
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 18081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo_db
    links:
      - mongo_db

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: alphacar/mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./../../var/mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD="root123"
      - MYSQL_DATABASE="alphacar"
      - MYSQL_USER="demo"
      - MYSQL_PASSWORD="demo123"
