version: '3'

services:

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: alphacar/backend
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./../src/node/koa2_backend:/root/koa2_backend:rw
    environment:
      - MONGODB_URL=mongodb://mongo_db:27017/alphacar
    command: bash -c "sleep 10; cd /root/koa2_backend; npm run prd; tail -f /dev/null;"
    links:
      - ipfs_node
      - mongo_db

  ipfs_node:
    build:
      context: ./ipfs_node
      dockerfile: Dockerfile
    image: alphacar/ipfs_node
    container_name: ipfs_node
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
    volumes:
      - ./../../var/ipfs:/root/.ipfs:rw
    command: /root/start.sh

  mongo_db:
    build:
      context: ./mongodb
      dockerfile: Dockerfile
    image: alphacar/mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - ./../../var/mongodb:/data/db:rw

  rockmongo:
    image: maichong/rockmongo
    container_name: rockmongo
    ports:
      - "18080:80"
    environment:
      #- MONGO_PORT_27017_TCP_ADDR="0.0.0.0"
      - MONGO_PORT_27017_TCP_ADDR="mongo_db"
      - MONGO_HOST="lc_mongodb"
      - S="0.0.0.0:80"
    links:
      - mongo_db

  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    image: alphacar/mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./../../var/mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD="root123"
      - MYSQL_DATABASE="alphacar"
      - MYSQL_USER="demo"
      - MYSQL_PASSWORD="demo123"
