FROM nginx:1.15

MAINTAINER leo chan <leochan007@163.com>

ENV DEBIAN_FRONTEND noninteractive

COPY nginx.conf /etc/nginx/nginx.conf

COPY alphacar_browser.conf /etc/nginx/conf.d/alphacar_browser.conf
