swagger: "2.0"

info:
  title: "AlphaCar Blockchain API"
  version: "1.0"

consumes:
  - application/json
produces:
  - application/json

basePath: /

paths:
  /greeting/{name}:
    get:
      tags: [DEMO]
      summary: Generate greeting
      description: Generates a greeting message.
      #x-swagger-router-controller: app.controller.index_ctl
      #operationId: post_greeting
      produces:
        - text/plain
      parameters:
        - name: name
          in: path
          description: Name of the person to greet.
          required: true
          type: string
      responses:
        200:
          description: greeting response
          schema:
            type: string
          examples:
            "text/plain": "Hello! John"

  /ubi_info/latest:
    get:
      tags: [UBI Info]
      summary: get latest tx
      description: get latest tx
      x-swagger-router-controller: app.controller.mongo_ctl
      operationId: getLatestUBIInfo
      produces:
        - application/json
      responses:
        200:
          description: infos response
          schema:
            $ref: "#/definitions/UBIInfo"

  /ubi_info/index/{ubi_code}:
    get:
      tags: [UBI Info]
      summary: get latest tx
      description: get latest tx
      x-swagger-router-controller: app.controller.mongo_ctl
      operationId: getUbiInfo
      produces:
        - application/json
      parameters:
        - name: ubi_code
          in: path
          description: the ubi_code string.
          required: true
          type: string
      responses:
        200:
          description: infos response
          schema:
            $ref: "#/definitions/UBIInfo"

  /ubi_info_lst:
    get:
      tags: [UBI Info]
      summary: get all txs by date
      description: get all txs by date
      x-swagger-router-controller: app.controller.mongo_ctl
      operationId: getUbiInfoList
      produces:
        - application/json
      parameters:
        - name: search_type
          in: query
          description: the search_type string.
          required: true
          type: string
        - name: search_txt
          in: query
          description: the search_txt string.
          required: true
          type: string
      responses:
        200:
          description: UBIInfos response
          schema:
            type: "array"
            items:
              $ref: "#/definitions/UBIInfo"

  /ubi_info_lst/all:
    get:
      tags: [UBI Info]
      summary: get all txs by date
      description: get all txs by date
      x-swagger-router-controller: app.controller.mongo_ctl
      operationId: getAllUbiInfoList
      produces:
        - application/json
      responses:
        200:
          description: UBIInfos response
          schema:
            type: "array"
            items:
              $ref: "#/definitions/UBIInfo"

definitions:

  User:
    type: "object"
    properties:
      name:
        type: "string"
      driving_license:
        type: "string"

  CarInfo:
    type: "object"
    properties:
      car_type:
        type: "string"
      vin_code:
        type: "string"

  UBIInfo:
    type: "object"
    properties:
      ubi_code:
        type: "string"
      timestamp:
        type: "integer"
        format: "int64"
      user:
        $ref: "#/definitions/User"
      carinfo:
        $ref: "#/definitions/CarInfo"
      start_date:
        type: "string"
      end_date:
        type: "string"
      price:
        type: "number"
        format: "double"
